branches:
  only:
    - master
environment:
  PYTHONPATH: .
language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# command to run tests
script:
  - bash run_test.sh -c -a
